// Exploratory browser audit against audit-host.mjs. Runtime cookies stay ignored.
import { chromium, expect } from '@playwright/test';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { resolve, join } from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../..');
const dir=import.meta.dirname, runtime=join(root,'.manual/audit-2026-09-08');
const config=JSON.parse(await readFile(join(runtime,'connection.json'),'utf8'));
const phase=process.argv[2]??'explore';
const shots=join(dir,'screenshots');await mkdir(shots,{recursive:true});
const browser=await chromium.launch({headless:true});
let state;try{state=JSON.parse(await readFile(join(runtime,'browser-state.json'),'utf8'));}catch{}
const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:1440,height:1000},storageState:state});
const page=await context.newPage();page.setDefaultTimeout(7000);
const errors=[],consoleErrors=[],failed=[],results=[];
await page.addInitScript(()=>{window.auditCsp=[];document.addEventListener('securitypolicyviolation',e=>window.auditCsp.push({directive:e.violatedDirective,source:e.sourceFile,line:e.lineNumber,blocked:e.blockedURI,sample:e.sample}));});
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
page.on('requestfailed',r=>failed.push({url:new URL(r.url()).pathname,error:r.failure()?.errorText}));
function cli(...args){let out;try{out=execFileSync(join(root,'target/release/projectctl'),['--socket',config.socket,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']});}catch(e){if(e.status!==9)throw e;out=e.stdout;}return JSON.parse(out).data;}
const project=config.projects[0].id, base=`/api/v1/projects/${project}`;
const getCard=id=>cli('get',`${base}/cards/${id}`);
async function settle(){await expect(page.locator('.asidebottom')).toContainText('Connected to host');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForFunction(()=>!/^Loading (board|planning|calendar|timeline|date)/m.test(document.querySelector('main')?.innerText??''));}
async function shot(name){await settle();await page.screenshot({path:join(shots,`${name}.png`),fullPage:true});}
async function check(id,name,fn){const start=Date.now();try{const detail=await fn();results.push({id,name,status:'pass',detail,ms:Date.now()-start});}catch(e){results.push({id,name,status:'fail',error:String(e),ms:Date.now()-start});await shot(`${phase}-${id}-failure`).catch(()=>{});}console.log(JSON.stringify(results.at(-1)));await writeFile(join(dir,`checks/${phase}.json`),JSON.stringify({results,errors,consoleErrors,failed},null,2));}
async function nav(name){await page.getByRole('button',{name,exact:true}).click();}
async function close(){if(await page.getByRole('button',{name:'Close editor',exact:true}).count()){await page.getByRole('button',{name:'Close editor',exact:true}).click();if(await page.getByRole('button',{name:'Discard draft',exact:true}).isVisible())await page.getByRole('button',{name:'Discard draft',exact:true}).click();}}
async function route(view='list', extra=''){await page.goto(`${config.origin}/?view=${view}&project=${project}${extra}`);await page.getByLabel('Project',{exact:true}).waitFor();await settle();}
async function openCard(title){await route('list');await page.getByText(title,{exact:true}).click();await page.getByRole('dialog',{name:'Edit resource'}).waitFor();}
try{
 await page.goto(config.origin);
 await page.getByRole('button',{name:'Request access'}).or(page.getByLabel('Project',{exact:true})).waitFor();
 if(await page.getByRole('button',{name:'Request access'}).isVisible()){
  await page.getByRole('button',{name:'Request access'}).click();await page.getByText('Compare this challenge on the host machine:').waitFor();
  const pending=cli('pairings').items;const visible=await page.locator('body').innerText();const matching=pending.filter(p=>visible.includes(p.challenge));assert.equal(matching.length,1);cli('approve',matching[0].id,'--challenge',matching[0].challenge);
  await page.getByRole('button',{name:'I approved this browser',exact:true}).click();
 }
 await page.getByLabel('Project',{exact:true}).waitFor();await context.storageState({path:join(runtime,'browser-state.json')});
 if(phase==='explore'){
  await check('01','Seven views render with populated synthetic data',async()=>{const views=[];await page.getByLabel('Project',{exact:true}).selectOption(project);for(const [label,key] of [['Focus','focus'],['Projects','projects'],['Board','board'],['Calendar','calendar'],['Timeline','gantt'],['List','list'],['Updates','updates']]){await nav(label);await page.getByRole('heading',{level:1}).waitFor();await page.locator('main').getByText(/Loading/).waitFor({state:'hidden'}).catch(()=>{});await shot(`desktop-${key}`);views.push({view:key,text:(await page.locator('main').innerText()).slice(0,14000),url:page.url()});}await writeFile(join(dir,'checks/views.json'),JSON.stringify(views,null,2));return views.map(v=>v.view);});
  await check('02','Create card through shared UI and preserve after reload',async()=>{await route();await page.getByRole('button',{name:'Add card',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('Created through browser — QA');await page.getByLabel('Priority',{exact:true}).selectOption('urgent');await page.getByLabel('Start',{exact:true}).fill('2026-09-09');await page.getByLabel('End',{exact:true}).fill('2026-09-12');await page.getByLabel('Labels',{exact:true}).fill('qa, browser');await page.getByLabel('Description',{exact:false}).fill('Browser created synthetic task.');await page.getByRole('button',{name:'Create',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.reload();await page.getByText('Created through browser — QA',{exact:true}).waitFor();return 'Created, visible, persisted';});
  await check('03','Cancel dirty editor preserves draft until explicit discard',async()=>{await openCard('Draft-loss probe');await page.getByLabel('Title',{exact:true}).fill('Unsaved cancel probe');await page.getByRole('button',{name:'Close editor',exact:true}).click();await expect(page.getByText('Discard your unsaved draft?',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Keep editing',exact:true}).click();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Unsaved cancel probe');await close();return 'Dirty guard works on Close';});
  await check('04','Pin action must preserve unsaved card edits',async()=>{await openCard('Draft-loss probe');await page.getByLabel('Title',{exact:true}).fill('Unsaved pin probe');await page.getByRole('button',{name:/^(Pin to focus|Remove from focus)$/}).click();await page.getByRole('dialog').waitFor({state:'hidden'});const card=getCard(config.cards[4].id);await shot('bug-draft-lost-on-pin');assert.equal(card.metadata.title,'Unsaved pin probe','Editor closed and unsaved title was discarded by focus mutation');});
  await check('05','List milestone choice should not affect Board primary action',async()=>{await close();await route('list');await page.getByLabel('Resource type',{exact:true}).selectOption('milestones');await nav('Board');await shot('bug-board-add-milestone');const button=await page.locator('.heading button').innerText();assert.match(button,/Add card/,'Board primary action inherited milestone collection');});
  await check('06','Calendar date and layout survive reload',async()=>{await route('calendar');await page.getByLabel('Calendar layout',{exact:true}).selectOption('week');await page.getByLabel('Go to date',{exact:true}).fill('2026-10-13');await shot('calendar-october-week');const before={layout:await page.getByLabel('Calendar layout',{exact:true}).inputValue(),date:await page.getByLabel('Go to date',{exact:true}).inputValue(),url:page.url()};await page.reload();await page.getByLabel('Calendar layout',{exact:true}).waitFor();const after={layout:await page.getByLabel('Calendar layout',{exact:true}).inputValue(),date:await page.getByLabel('Go to date',{exact:true}).inputValue(),url:page.url()};await writeFile(join(dir,'checks/calendar-persistence.json'),JSON.stringify({before,after},null,2));assert.deepEqual(after,before,'Calendar date/layout reset on reload');});
  await check('07','Body search works in List and matches no unrelated rows',async()=>{await route('list');await page.getByLabel('Search content',{exact:true}).fill('nebula-13');await page.getByText('QA work package 13',{exact:true}).waitFor();await expect(page.getByText('Design system foundations',{exact:true})).not.toBeVisible();await shot('search-body-list');return 'Body search resolves QA work package 13';});
  await check('08','Empty state exposes meaningful action',async()=>{await route('board');await page.getByLabel('Project',{exact:true}).selectOption(config.projects[2].id);await shot('empty-board');return (await page.locator('main').innerText()).slice(0,3500);});
  await check('09','Archive card and inspect recovery affordances',async()=>{await openCard('Archive probe');await page.getByLabel('Archived',{exact:true}).check();await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await expect(page.getByText('Archive probe',{exact:true})).not.toBeVisible();await page.getByLabel('Search content',{exact:true}).fill('Archive probe');await expect(page.getByText('No items match this selection.',{exact:true})).toBeVisible();await shot('archive-no-retrieval');assert.equal(getCard(config.cards[7].id).metadata.archived,true);return 'Archive persisted; normal List and search hide it, no archive control visible';});
  await check('10','Mobile view layout and available controls at 390 × 844',async()=>{await page.setViewportSize({width:390,height:844});const measurements=[];for(const [label,key] of [['Focus','focus'],['Board','board'],['Calendar','calendar'],['Timeline','gantt'],['List','list'],['Updates','updates']]){await route(key);await page.getByRole('heading',{level:1}).waitFor();await shot(`mobile-${key}`);measurements.push(await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,controls:[...document.querySelectorAll('button,input,select')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0).map(e=>({text:e.getAttribute('aria-label')||e.textContent?.trim().slice(0,80),width:Math.round(e.getBoundingClientRect().width),height:Math.round(e.getBoundingClientRect().height)}))})));}await writeFile(join(dir,'checks/mobile-layout.json'),JSON.stringify(measurements,null,2));return measurements.map((m,i)=>({view:['focus','board','calendar','gantt','list','updates'][i],viewport:m.viewport,scrollWidth:m.scrollWidth,smallTargets:m.controls.filter(c=>c.height<44||c.width<44).length}));});
  await check('11','Mobile card editor',async()=>{await openCard('Design system foundations');await shot('mobile-editor-top');await page.getByLabel('Description',{exact:false}).scrollIntoViewIfNeeded();await shot('mobile-editor-details');await close();return 'Editor opens and scrolls';});
  await check('12','Dark view rendering and persistence',async()=>{await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Workspace settings',exact:true}).click();await page.getByLabel('Theme',{exact:true}).selectOption('dark');await shot('settings-dark');await page.getByRole('button',{name:'Close settings',exact:true}).click();for(const v of ['board','calendar','gantt']){await route(v);await shot(`dark-${v}`);}await page.reload();assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).colorScheme),'dark');await page.getByRole('button',{name:'Workspace settings',exact:true}).click();await page.getByLabel('Theme',{exact:true}).selectOption('light');await page.getByRole('button',{name:'Close settings',exact:true}).click();return 'Dark renders and survives reload';});
 }
 if(phase==='interactions'){
  await check('20','Competing browser edits retain stale draft and preserve first save',async()=>{
   await openCard('Conflict probe');const other=await context.newPage();other.setDefaultTimeout(7000);await other.goto(page.url());await other.getByLabel('Title',{exact:true}).waitFor();
   await other.getByLabel('Title',{exact:true}).fill('Conflict probe — stale browser draft');await page.getByLabel('Title',{exact:true}).fill('Conflict probe — first saved');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
   await other.getByRole('button',{name:'Save changes',exact:true}).click();await other.getByRole('alert').filter({hasText:/changed since you opened/i}).waitFor();assert.equal(await other.getByLabel('Title',{exact:true}).inputValue(),'Conflict probe — stale browser draft');assert.equal(getCard(config.cards[6].id).metadata.title,'Conflict probe — first saved');await other.screenshot({path:join(shots,'two-tab-conflict.png'),fullPage:true});await other.close();return 'Conflict stops overwrite, draft remains visible; current record is raw JSON';
  });
  await check('21','Invalid schedule is blocked before saving',async()=>{await route('list');await page.getByRole('button',{name:'Add card',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('Invalid date probe');await page.getByLabel('Start',{exact:true}).fill('2026-09-15');await page.getByLabel('End',{exact:true}).fill('2026-09-10');await page.getByRole('button',{name:'Create',exact:true}).click();const validation=await page.getByLabel('End',{exact:true}).evaluate(e=>({valid:e.validity.valid,message:e.validationMessage}));assert.equal(validation.valid,false);await shot('invalid-date-native-validation');await close();return validation;});
  await check('22','Required title rejects blank new card',async()=>{await route('list');await page.getByRole('button',{name:'Add card',exact:false}).click();await page.getByRole('button',{name:'Create',exact:true}).click();const validation=await page.getByLabel('Title',{exact:true}).evaluate(e=>({valid:e.validity.valid,message:e.validationMessage}));assert.equal(validation.valid,false);await close();return validation;});
  await check('23','Markdown remains safe and preview shows formatting',async()=>{await openCard('History probe');await page.getByLabel('Description',{exact:false}).fill('## Synthetic preview\n\n**Bold** and _italic_\n\n<script>window.auditInjected=1</script>\n\n![No remote image](https://example.com/audit-image.png)');await page.getByRole('button',{name:'Preview Markdown',exact:true}).click();await expect(page.getByRole('heading',{name:'Synthetic preview',exact:true})).toBeVisible();assert.equal(await page.evaluate(()=>window.auditInjected),undefined);assert.equal(await page.locator('dialog img').count(),0);await shot('markdown-preview');await close();return 'Formatting renders; raw script remains inert; no image element';});
  await check('24','History undo restores saved edit',async()=>{await openCard('History probe');await page.getByLabel('Title',{exact:true}).fill('History probe — edited');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await openCard('History probe — edited');await page.getByText('Change history',{exact:true}).click();await page.getByRole('button',{name:'First history page',exact:true}).click();await page.getByRole('button',{name:'Undo this change',exact:true}).first().click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(getCard(config.cards[5].id).metadata.title,'History probe');return 'Undo restored prior title';});
  await check('25','Update read state and unread filter',async()=>{await route('updates');await page.getByRole('button').filter({hasText:'Prototype tested on synthetic fixtures'}).click();await page.getByRole('button',{name:'Mark read',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByLabel('Unread only',{exact:true}).check();await expect(page.getByRole('button').filter({hasText:'Prototype tested on synthetic fixtures'})).not.toBeVisible();await shot('updates-unread-filter');return 'Mark read persisted; unread filter removes it';});
  await check('26','Browser Back returns previous application view',async()=>{await route('focus');await nav('Board');await nav('Calendar');await page.goBack();const heading=await page.getByRole('heading',{level:1}).innerText();await shot('browser-back-state');assert.equal(heading,'Board.','Application navigation does not create view history');});
  await check('27','Mobile Sign out reachable as named action',async()=>{await route('focus');await page.setViewportSize({width:390,height:844});await shot('mobile-missing-sign-out');assert.equal(await page.getByRole('button',{name:'Sign out',exact:true}).isVisible(),true,'Sign out hidden on mobile and no More menu exposed');});
  await check('28','Layout boundaries at 320, 768 and 1280 pixels',async()=>{const list=[];for(const width of [320,768,1280]){await page.setViewportSize({width,height:900});for(const v of ['board','calendar','gantt']){await route(v);await page.getByRole('heading',{level:1}).waitFor();await shot(`layout-${width}-${v}`);list.push({view:v,...await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('button')].filter(e=>e.getBoundingClientRect().width>0).length}))});}}await writeFile(join(dir,'checks/layout-boundaries.json'),JSON.stringify(list,null,2));assert(list.every(v=>v.scrollWidth<=v.width),JSON.stringify(list.filter(v=>v.scrollWidth>v.width)));return list;});
  await check('29','Pinned cards obey selected project and title filter',async()=>{await page.setViewportSize({width:1440,height:1000});await page.goto(`${config.origin}/?view=list&project=${config.projects[1].id}`);await page.getByText('Separate project focus probe',{exact:true}).click();if(await page.getByRole('button',{name:'Pin to focus',exact:true}).count()){await page.getByRole('button',{name:'Pin to focus',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});}else await close();await route('focus');await page.getByLabel('Filter loaded titles',{exact:true}).fill('Design system');await shot('focus-scope-mismatch');await expect(page.getByText('Separate project focus probe',{exact:true})).not.toBeVisible();});
 }
 if(phase==='followup'){
  await check('30','Populated screenshots after data and widget readiness',async()=>{const metrics=[];for(const theme of ['light','dark']){await route('list');await page.getByRole('button',{name:'Workspace settings',exact:true}).click();await page.getByLabel('Theme',{exact:true}).selectOption(theme);await page.getByRole('button',{name:'Close settings',exact:true}).click();for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});for(const v of ['focus','projects','board','calendar','gantt','list','updates']){await route(v);await shot(`verified-${theme}-${width}-${v}`);metrics.push({theme,width,view:v,...await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,documentHeight:document.documentElement.scrollHeight,calendar:document.querySelector('.ec')?.getBoundingClientRect().toJSON(),calendarRows:[...document.querySelectorAll('.ec-body .ec-row')].map(e=>e.getBoundingClientRect().toJSON()),events:document.querySelectorAll('.ec-event').length,boardCards:document.querySelectorAll('[data-board-card]').length,csp:window.auditCsp}))});}}}await writeFile(join(dir,'checks/settled-view-metrics.json'),JSON.stringify(metrics,null,2));return '28 populated light/dark desktop/narrow screenshots with readiness checks';});
  await check('31','Focus respects project and search after all pins load',async()=>{await page.setViewportSize({width:1440,height:1000});await route('focus');await page.getByText('Separate project focus probe',{exact:true}).waitFor();await page.getByLabel('Filter loaded titles',{exact:true}).fill('Design system');await shot('verified-focus-scope-mismatch');await expect(page.getByText('Separate project focus probe',{exact:true})).not.toBeVisible();});
  await check('32','Editing title must preserve an existing comma-containing label',async()=>{const input=join(runtime,'tag-probe.json');await writeFile(input,JSON.stringify({title:'Comma tag probe',labels:['Research, discovery']}));const card=cli('command','POST',`${base}/cards`,'--json-file',input).result;await openCard('Comma tag probe');await shot('comma-tag-before');await page.getByLabel('Title',{exact:true}).fill('Comma tag probe — title edited');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});const saved=getCard(card.id);await openCard('Comma tag probe — title edited');await shot('comma-tag-after');await close();assert.deepEqual(saved.metadata.labels,['Research, discovery'],'Unedited label was split into two tags by an unrelated title edit');});
  await check('33','Duplicate tag input is handled through visible feedback',async()=>{await route('list');await page.getByRole('button',{name:'Add card',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('Duplicate tags probe');await page.getByLabel('Labels',{exact:true}).fill('qa, qa');await page.getByRole('button',{name:'Create',exact:true}).click();await page.getByRole('alert').waitFor();const text=await page.getByRole('alert').innerText();await shot('duplicate-tags-generic-error');await close();return {feedback:text,interpretation:'Server rejects duplicate labels; inspect whether message identifies the offending field'};});
  await page.getByRole('button',{name:'Workspace settings',exact:true}).click();await page.getByLabel('Theme',{exact:true}).selectOption('light');await page.getByRole('button',{name:'Close settings',exact:true}).click();
 }
 if(phase==='focus-confirm'){
  await check('34','Pin in another project then verify Focus selection scope',async()=>{await page.goto(`${config.origin}/?view=list&project=${config.projects[1].id}`);await settle();await page.getByText('Separate project focus probe',{exact:true}).click();await page.getByLabel('Title',{exact:true}).waitFor();const pin=page.getByRole('button',{name:/^(Pin to focus|Remove from focus)$/});await expect(pin).toBeEnabled();if((await pin.innerText())==='Pin to focus'){await pin.click();await page.getByRole('dialog').waitFor({state:'hidden'});}else await close();assert(cli('get','/api/v1/workspace/focus').items.some(p=>p.card_id===config.other.id));await route('focus');await expect(page.getByText('Separate project focus probe',{exact:true})).toBeVisible();await page.getByLabel('Filter loaded titles',{exact:true}).fill('Design system');await shot('verified-focus-scope-mismatch');await expect(page.getByText('Separate project focus probe',{exact:true})).not.toBeVisible();});
 }
 if(phase==='completion'){
  await check('35','Create milestone and attach to a card by title search',async()=>{await route('list');await page.getByLabel('Resource type',{exact:true}).selectOption('milestones');await page.getByRole('button',{name:'Add milestone',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('Browser milestone — QA');await page.getByLabel('Due date',{exact:true}).fill('2026-09-25');await page.getByRole('button',{name:'Create',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByText('Browser milestone — QA',{exact:true}).waitFor();await openCard('Design system foundations');await page.getByLabel('Search for',{exact:true}).selectOption('milestone');await page.getByLabel('Find by title',{exact:true}).fill('Browser milestone');await page.getByRole('button',{name:'Find resources',exact:true}).click();await page.getByRole('button',{name:'Browser milestone — QA',exact:true}).click();const chosen=await page.getByLabel('Milestone ID',{exact:true}).inputValue();assert(chosen);await shot('milestone-title-picker-fills-id');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(getCard(config.cards[0].id).metadata.milestone_id,chosen);return 'Milestone created in UI and linked by title; chosen relationship is still shown as raw ID';});
  await check('36','Real offline save retains draft and succeeds after explicit retry',async()=>{await openCard('History probe');await page.getByLabel('Title',{exact:true}).fill('History probe — recovered offline save');await context.setOffline(true);await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('button',{name:'Retry same command',exact:true}).waitFor();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'History probe — recovered offline save');await page.screenshot({path:join(shots,'offline-retained-draft.png'),fullPage:true});assert.equal(getCard(config.cards[5].id).metadata.title,'History probe');await context.setOffline(false);await page.getByRole('button',{name:'Retry same command',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(getCard(config.cards[5].id).metadata.title,'History probe — recovered offline save');return 'Actual browser offline mode caused failed request; original draft retained, explicit retry saved once. This is not a lost response after commit.';});
  await check('37','Calendar Today agrees with workspace date across browser timezones',async()=>{const tz=await browser.newContext({ignoreHTTPSErrors:true,timezoneId:'Pacific/Honolulu',viewport:{width:1440,height:1000},storageState:await context.storageState()});try{const p=await tz.newPage();await p.goto(`${config.origin}/?view=calendar&project=${project}`);await p.getByLabel('Go to date',{exact:true}).waitFor();await expect(p.locator('.asidebottom')).toContainText('Connected to host');const workspaceDate=await p.locator('.topbar .date').innerText();await p.getByRole('button',{name:'Today',exact:true}).click();const calendarDate=await p.getByLabel('Go to date',{exact:true}).inputValue();await p.screenshot({path:join(shots,'timezone-today-mismatch.png'),fullPage:true});assert.equal(calendarDate,workspaceDate,`Workspace Today ${workspaceDate}, calendar Today ${calendarDate} with browser Pacific/Honolulu`);return {workspaceDate,calendarDate};}finally{await tz.close();}});
 }
 if(phase==='milestone-confirm'){
  await check('38','Previously browser-created milestone can be linked through title picker',async()=>{await route('list');await page.getByLabel('Resource type',{exact:true}).selectOption('milestones');await page.getByText('Browser milestone — QA',{exact:true}).waitFor();await openCard('Design system foundations');await page.locator('label').filter({hasText:/^Search for/}).locator('select').selectOption('milestone');await page.getByLabel('Find by title',{exact:true}).fill('Browser milestone');await page.getByRole('button',{name:'Find resources',exact:true}).click();await page.getByRole('button',{name:'Browser milestone — QA',exact:true}).click();const chosen=await page.getByLabel('Milestone ID',{exact:true}).inputValue();assert(chosen);await shot('milestone-title-picker-fills-id');await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(getCard(config.cards[0].id).metadata.milestone_id,chosen);return 'Creation from check35 persisted; title lookup and assignment now verified. Check35 exact accessible-label locator was a harness mismatch.';});
 }
 if(phase==='inspect'){await route(process.argv[3]??'board');await shot(`inspect-${process.argv[3]??'board'}`);console.log(await page.locator('body').innerText());}
 await context.storageState({path:join(runtime,'browser-state.json')});
}catch(e){await page.screenshot({path:join(runtime,'setup-error.png'),fullPage:true});await writeFile(join(runtime,'setup-error.txt'),await page.locator('body').innerText());throw e;}finally{await writeFile(join(dir,`checks/${phase}.json`),JSON.stringify({results,errors,consoleErrors,failed,browser:browser.version()},null,2));await browser.close();}
